package com.gmavrommatis.config.r2dbc.domain;

import io.micronaut.core.annotation.Introspected;
import io.micronaut.data.annotation.GeneratedValue;
import io.micronaut.data.annotation.Id;
import io.micronaut.data.annotation.MappedEntity;
import io.micronaut.data.annotation.MappedProperty;
import io.micronaut.serde.annotation.Serdeable;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * The {@code Specialty} entity represents a specific veterinary specialty (e.g., surgery,
 * dermatology) within the Pet Clinic domain.
 *
 * <p>This class is mapped to the <code>petclinic.specialties</code> table and supports JSON
 * serialization/deserialization via Micronaut Serde.
 *
 * @author GewrgiosMmavrommatis
 * @version 1.0
 */
@Introspected
@Serdeable
@MappedEntity(value = "specialties", schema = "petclinic")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Specialty {

  /**
   * The primary key of the specialty.
   *
   * <p>Auto-generated by the database.
   */
  @Id @GeneratedValue private Long id;

  /**
   * The unique name of the specialty.
   *
   * <p>Mapped to the <code>name</code> column in the database. Cannot be null.
   */
  @MappedProperty(value = "name")
  private String name;
}
