micronaut.application.name=pet-clinic


#reference: https://guides.micronaut.io/latest/micronaut-data-r2dbc-repository-maven-java.html
r2dbc.datasources.default.url=r2dbc:postgresql://localhost:5432/pet_clinic
r2dbc.datasources.default.username=pet_clinic
r2dbc.datasources.default.password=petclinic
r2dbc.datasources.default.pool.enabled=true
# Optional: Connection pool size
#r2dbc.datasources.default.options.maximum-pool-size=5

# Micronaut Data R2DBC dialect
micronaut.data.r2dbc.dialect=POSTGRES


#Reference: https://docs.micronaut.io/latest/guide/configurationreference.html#io.micronaut.http.server.HttpServerConfiguration
micronaut.server.thread-selection=AUTO