micronaut:
  application:
    name: pet-clinic

  server:
    thread-selection: AUTO
    #Reference: https://guides.micronaut.io/latest/micronaut-cors-gradle-java.html
    cors:
      enabled: true   # turn on CORS support
      configurations:
        ui:
          allowed-origins:
            - http://127.0.0.1:8000
            - http://127.0.0.1:8888
          allowed-headers: [ Authorization, Content-Type ]
          allowed-methods: [ GET, POST, PUT, PATCH, DELETE, OPTIONS ]
          allow-credentials: true

  security:
    enabled: true                 # turn on the security module outright
    #Reference: https://micronaut-projects.github.io/micronaut-security/latest/guide/#builtInHandlers
    # use Authentication Mode Bearer
    authentication: idtoken
    endpoints:
      login:
        enabled: true       #by default is true when security session is enabled
        post-content-types:
          - application/json
      logout:
        get-allowed: true
    #Reference: https://micronaut-projects.github.io/micronaut-security/latest/guide/index.html#redirection
    redirect:
      login-success: http://localhost:8080/    # where to send the browser after login
      #login-success: /secure/anonymous    # where to send the browser after login
      logout: "http://localhost:8888/realms/pet-clinic/protocol/openid-connect/logout?post_logout_redirect_uri=http://localhost:8080/oauth/login/keycloak&client_id=pet-clinic"
      prior-to-login: true   # optional: return to originally requested URL
      #Reference: https://micronaut-projects.github.io/micronaut-security/latest/guide/index.html#io.micronaut.security.config.RedirectConfigurationProperties$UnauthorizedRedirectConfigurationProperties
      unauthorized:
        url: /oauth/login/keycloak              # <— redirect here instead of 401
    #Reference: https://micronaut-projects.github.io/micronaut-security/latest/guide/index.html#io.micronaut.security.config.SecurityConfigurationProperties
    intercept-url-map:
      - pattern: /oauth/login/**
        access: isAnonymous()
      - pattern: /oauth/callback/**
        access: isAnonymous()
      - pattern: /login
        access: isAnonymous()
      - pattern: /**
        access: isAuthenticated()
    token:
      jwt:
        enabled: true
      # store token in an HttpOnly cookie named JWT
      #Reference: https://micronaut-projects.github.io/micronaut-security/latest/guide/index.html#io.micronaut.security.token.cookie.TokenCookieConfigurationProperties
      cookie:
        enabled: true
        cookie-name: JWT
        cookie-path: /
        cookie-http-only: true
        cookie-secure: false            # true in HTTPS/prod
    # This tells Micronaut how to obtain tokens from Keycloak for /login
    oauth2:
      clients:
        keycloak:
          grant-type: authorization_code
          client-id: pet-clinic
          client-secret: petclinic-secret
          authorization:
            url: http://localhost:8888/realms/pet-clinic/protocol/openid-connect/auth
          token:
            url: http://localhost:8888/realms/pet-clinic/protocol/openid-connect/token
          openid:
            issuer: http://localhost:8888/realms/pet-clinic
          scopes:
            - openid            # REQUIRED to receive id_token
            - profile
            - email
            - offline_access     # optional
  data:
    r2dbc:
      dialect: POSTGRES

logger:
  levels:
    org.mongodb.driver.connection: DEBUG
    reactor.core.publisher: TRACE
#    org.mongodb.driver.cluster: DEBUG
    org.mongodb.driver.protocol.command: DEBUG
    org.mongodb.driver.protocol.query: DEBUG


# Start the WebSocket server
websocket:
  server:
    enabled: true

r2dbc:
  datasources:
    default:
      url: r2dbc:postgresql://localhost:5432/pet_clinic
      username: pet_clinic
      password: petclinic
      options:
        # Which connection-pool implementation to use. pool value means
        #“use the built-in R2DBC Pool (io.r2dbc.pool.ConnectionPool)” rather than a direct, non-pooled driver.
        driver: pool
        protocol: postgres #The R2DBC URL sub-protocol, i.e. which vendor driver to load under the hood.
        maxSize: 20 #Maximum number of connections the pool will hold.
        initialSize: 4 #How many connections to open immediately on startup.
        poolName: r2dbc #A logical name for the pool instance.
        registerJmx: false # Don’t expose via JMX

#mongo Reference: https://micronaut-projects.github.io/micronaut-mongodb/5.5.0/guide/configurationreference.html
mongodb:
  uri: "mongodb://localhost:27017/petclinic"
  # 1) Enable POJO mapping (scans your package for getters/setters)
  package-names:
    - "com.gmavrommatis.config.mongo.document"
  automatic-class-models: true
  # 2) All our pool settings in one place
  connection-pool:
    max-size: 5                    # connectionsPerHost
    min-size: 5                     # minConnectionsPerHost
    max-wait-time: 2s               # maxWaitTime
    max-connection-idle-time: 60s   # maxConnectionIdleTime
    max-connection-life-time: 120s  # maxConnectionLifeTime
    # (Reactive driver no longer uses threadsAllowedToBlock…)
    maintenance-initial-delay: 0s
    maintenance-frequency: 5m