micronaut:
  application:
    name: pet-clinic

  server:
    thread-selection: AUTO
    #Reference: https://guides.micronaut.io/latest/micronaut-cors-gradle-java.html
    cors:
      enabled: true   # turn on CORS support
      configurations:
        ui:
          allowed-origins:
            - "http://127.0.0.1:8000"
            - "http://localhost:8000"
  openapi:
    views:
      #swagger-ui.enabled=true: Enables generation/serving of Swagger UI (the classic Swagger web-based UI).
      #swagger-ui.theme=flattop: Changes look & feel of the Swagger UI: colors, spacing, fonts, and some component styles to flattop visual theme
      spec: "swagger-ui.enabled=true,swagger-ui.theme=flattop"
    property:
      naming:
        strategy: "KEBAB_CASE" #Controls how property names (fields in DTOs / schemas) are written in the generated OpenAPI schema.
    target:
      file: "openapi.yml" #Tells the OpenAPI generator the target filename for the generated OpenAPI spec.
  router:
    static-resources:
      # Serve any files placed under META-INF/swagger on the classpath
      # Example: target/classes/META-INF/swagger/myspecfile.yml
      swagger:
        # Classpath folder to serve
        paths: classpath:META-INF/swagger
        # Public URL mapping (all requests under /swagger/ will be served from the above classpath)
        # Example: http://localhost:8080/swagger/myspecfile.yml -> META-INF/swagger/myspecfile.yml
        mapping: /swagger/**

      # Serve the Swagger UI static assets that Micronaut places under
      # META-INF/swagger/views/swagger-ui (when swagger-ui is enabled).
      swagger-ui:
        # Classpath folder containing the UI HTML/CSS/JS
        paths: classpath:META-INF/swagger/views/swagger-ui
        # Public URL mapping for the UI
        # Example: http://localhost:8080/swagger-ui/index.html loads the interactive Swagger UI
        mapping: /swagger-ui/**
  data:
    r2dbc:
      dialect: POSTGRES

#Reference: https://micronaut-projects.github.io/micronaut-kafka/latest/guide/#kafkaQuickStart:~:text=Copy%20to%20Clipboard-,Configuring%20Kafka,-The%20minimum%20requirement
kafka:
  bootstrap:
    servers: localhost:9092

logger:
  levels:
#    org.mongodb.driver.connection: DEBUG
#    reactor.core.publisher: TRACE
#    org.mongodb.driver.cluster: DEBUG
#    org.mongodb.driver.protocol.command: DEBUG
#    org.mongodb.driver.protocol.query: DEBUG
#    org.apache.kafka: DEBUG
#    org.apache.kafka.clients.producer: DEBUG
#    io.micronaut.configuration.kafka: TRACE


# Start the WebSocket server
websocket:
  server:
    enabled: true

r2dbc:
  datasources:
    default:
      url: r2dbc:postgresql://localhost:5432/pet_clinic
      username: pet_clinic
      password: petclinic
      options:
        # Which connection-pool implementation to use. pool value means
        #“use the built-in R2DBC Pool (io.r2dbc.pool.ConnectionPool)” rather than a direct, non-pooled driver.
        driver: pool
        protocol: postgres #The R2DBC URL sub-protocol, i.e. which vendor driver to load under the hood.
        maxSize: 20 #Maximum number of connections the pool will hold.
        initialSize: 4 #How many connections to open immediately on startup.
        poolName: r2dbc #A logical name for the pool instance.
        registerJmx: false # Don’t expose via JMX

#mongo Reference: https://micronaut-projects.github.io/micronaut-mongodb/5.5.0/guide/configurationreference.html
mongodb:
  uri: "mongodb://localhost:27017/petclinic"
  # 1) Enable POJO mapping (scans your package for getters/setters)
  package-names:
    - "com.gmavrommatis.config.mongo.document"
  automatic-class-models: true
  # 2) All our pool settings in one place
  connection-pool:
    max-size: 5                    # connectionsPerHost
    min-size: 5                     # minConnectionsPerHost
    max-wait-time: 2s               # maxWaitTime
    max-connection-idle-time: 60s   # maxConnectionIdleTime
    max-connection-life-time: 120s  # maxConnectionLifeTime
    # (Reactive driver no longer uses threadsAllowedToBlock…)
    maintenance-initial-delay: 0s
    maintenance-frequency: 5m

