package com.gmavrommatis.config.domain.l1;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import io.micronaut.core.annotation.Introspected;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.persistence.*;
import java.util.HashSet;
import java.util.Set;
import lombok.*;

/**
 * The {@code Vet} entity represents a veterinarian in the Pet Clinic domain.
 *
 * <p>Each vet has a first and last name, and may have multiple specialties but at least 1. This
 * entity is mapped to the {@code vets} table in the {@code petclinic} schema.
 *
 * <p>Specialties are lazily loaded and ignored during JSON serialization to prevent recursion and
 * unnecessary database access.
 *
 * @author GewrgiosMmavrommatis
 */
@Introspected
@Serdeable
@Entity
@Table(name = "vets", schema = "petclinic")
@JsonInclude(JsonInclude.Include.NON_NULL)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Vet {

  /**
   * The primary key identifier for this vet.
   *
   * <p>Generated by the database using an identity column.
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  /**
   * The vet's first name.
   *
   * <p>Cannot be null.
   */
  @Column(name = "first_name", nullable = false)
  private String firstName;

  /**
   * The vet's last name.
   *
   * <p>Cannot be null.
   */
  @Column(name = "last_name", nullable = false)
  private String lastName;

  /**
   * The set of specialties assigned to this vet.
   *
   * <p>This is the owning side of a many-to-many relationship between the {@code Vet} and {@code
   * Specialty} entities. By default, the specialties collection is not loaded until first accessed
   * (<strong>LAZY</strong> fetch). Hibernate will use the {@code vet_specialties} join table (in
   * the {@code petclinic} schema) to map vets to specialties:
   *
   * <p>The {@code @JsonIgnore} annotation prevents this field from being serialized (e.g. to JSON),
   * avoiding infinite recursion or lazy-loading errors when returning a {@code Vet} via an HTTP
   * API.
   */
  @JsonIgnore
  @ManyToMany(fetch = FetchType.LAZY)
  @JoinTable(
      name = "vet_specialties",
      schema = "petclinic",
      joinColumns = @JoinColumn(name = "vet_id"),
      inverseJoinColumns = @JoinColumn(name = "specialty_id"))
  private Set<Specialty> specialties = new HashSet<>();
}
