package com.gmavrommatis.config.domain;

import io.micronaut.core.annotation.Introspected;
import io.micronaut.data.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import java.util.HashSet;
import java.util.Set;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * The {@code Specialty} entity represents a specific veterinary specialty (e.g., surgery,
 * dermatology) within the Pet Clinic domain.
 *
 * <p>This class is mapped to the <code>petclinic.specialties</code> table and supports JSON
 * serialization/deserialization via Micronaut Serde.
 *
 * @author GewrgiosMmavrommatis
 */
@Introspected
@Serdeable
@MappedEntity(value = "specialties", schema = "petclinic")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class SpecialtyRelated {

  /**
   * The primary key of the specialty.
   *
   * <p>Automatically generated by the persistence provider / database when a new record is
   * inserted. This field uniquely identifies a {@code SpecialtyRelated} instance.
   *
   * <p>Corresponds to the table primary key column (annotated with {@code @Id} and
   * {@code @GeneratedValue}).
   *
   * @see Id
   * @see GeneratedValue
   */
  @Id @GeneratedValue private Long id;

  /**
   * The unique name of the specialty.
   *
   * <p>Mapped to the {@code name} column in the {@code petclinic.specialties} table. This value
   * should be non-null and, in typical application logic, unique across specialties.
   *
   * <p>Validation (non-null / uniqueness) is not enforced here — apply database constraints or
   * validation annotations where appropriate (for example {@code @NotNull} and a unique DB index).
   *
   * @see io.micronaut.data.annotation.MappedProperty
   */
  @MappedProperty(value = "name")
  private String name;

  /**
   * The set of veterinarians associated with this specialty.
   *
   * <p>Represents the inverse side of a many-to-many relation between vets and specialties. The
   * owning side is expected to be on {@code VetRelated} (mapped by {@code specialties}).
   *
   * <p>The collection is initialized to an empty {@link HashSet} to avoid {@code
   * NullPointerException} when iterating or adding elements. Because this is a bidirectional
   * association, updates to this set should normally be mirrored on the owning side to keep both
   * sides consistent.
   *
   * <p>Be cautious with serialization / lazy-loading: when sending entities across layers or over
   * the wire, ensure the collection is handled appropriately (DTO mapping or explicit fetch).
   *
   * @see io.micronaut.data.annotation.Relation
   * @see VetRelated
   */
  @Relation(value = Relation.Kind.MANY_TO_MANY, mappedBy = "specialties")
  private Set<VetRelated> vets = new HashSet<>();
}
