package com.gmavrommatis.config.domain;

import io.micronaut.core.annotation.Introspected;
import io.micronaut.data.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import java.util.HashSet;
import java.util.Set;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * The {@code Specialty} entity represents a specific veterinary specialty (e.g., surgery,
 * dermatology) within the Pet Clinic domain.
 *
 * <p>This class is mapped to the <code>petclinic.specialties</code> table and supports JSON
 * serialization/deserialization via Micronaut Serde.
 *
 * @author GewrgiosMmavrommatis
 */
@Introspected
@Serdeable
@MappedEntity(value = "specialties", schema = "petclinic")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class SpecialtyRelated {

  /**
   * The primary key of the specialty.
   *
   * <p>Automatically generated by the persistence provider / database when a new record is
   * inserted. This field uniquely identifies a {@code SpecialtyRelated} instance.
   *
   * <p>Corresponds to the table primary key column (annotated with {@code @Id} and
   * {@code @GeneratedValue}).
   *
   * @see Id
   * @see GeneratedValue
   */
  @Id @GeneratedValue private Long id;

  /**
   * The unique name of the specialty.
   *
   * <p>Mapped to the {@code name} column in the {@code petclinic.specialties} table. This value
   * should be non-null and, in typical application logic, unique across specialties.
   *
   * <p>Validation (non-null / uniqueness) is not enforced here — apply database constraints or
   * validation annotations where appropriate (for example {@code @NotNull} and a unique DB index).
   *
   * @see io.micronaut.data.annotation.MappedProperty
   */
  @MappedProperty(value = "name")
  private String name;

  /**
   * The set of veterinarians associated with this specialty.
   *
   * <p>Represents the <strong>inverse side</strong> of a many-to-many relationship between
   * veterinarians and specialties. The owning side of the association is defined on
   * {@code VetRelated} via the {@code specialties} collection.
   *
   * <p>This side does <strong>not control</strong> the join table; it exists primarily for
   * navigation and consistency within the object model.
   *
   * <p>The collection is initialized to an empty {@link HashSet} to avoid {@link
   * NullPointerException} when iterating or adding elements.
   *
   * <p>Cascade options include {@code UPDATE} only. This allows synchronization of the
   * association when the owning side updates the relationship, without attempting to
   * persist or recreate {@code VetRelated} entities from this side.
   *
   * <p>{@code PERSIST} is intentionally avoided here because this entity is not responsible
   * for the lifecycle of veterinarians. Specialty entities are treated as shared reference
   * data, not aggregate roots that create vets.
   *
   * <p>As with any bidirectional association, updates should be mirrored on the owning side
   * to keep both sides consistent.
   *
   * <p>Be cautious with serialization and lazy-loading. This collection should not be
   * exposed directly in API responses; use DTOs or explicit fetch strategies instead.
   *
   * @see io.micronaut.data.annotation.Relation
   * @see VetRelated
   */
  @Relation(
      value = Relation.Kind.MANY_TO_MANY,
      mappedBy = "specialties",
      cascade = {Relation.Cascade.PERSIST, Relation.Cascade.UPDATE})
  private Set<VetRelated> vets = new HashSet<>();
}
