package com.gmavrommatis.config.domain;

import com.fasterxml.jackson.annotation.JsonInclude;
import io.micronaut.core.annotation.Introspected;
import io.micronaut.data.annotation.GeneratedValue;
import io.micronaut.data.annotation.Id;
import io.micronaut.data.annotation.MappedEntity;
import io.micronaut.data.annotation.MappedProperty;
import io.micronaut.serde.annotation.Serdeable;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * The {@code Vet} entity represents a veterinarian in the Pet Clinic domain.
 *
 * <p>Mapped to the <code>petclinic.vets</code> table, this class supports JSON
 * serialization/deserialization via Micronaut Serde, and ignores null properties during
 * serialization.
 *
 * @author GewrgiosMmavrommatis
 */
@Introspected
@Serdeable
@MappedEntity(value = "vets", schema = "petclinic")
@JsonInclude(JsonInclude.Include.NON_NULL)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Vet {

  /**
   * The primary key identifier for this veterinarian.
   *
   * <p>Automatically generated by the database.
   */
  @GeneratedValue @Id private Long id;

  /**
   * The veterinarian's first name.
   *
   * <p>Mapped to the <code>first_name</code> column in the database. Cannot be null.
   */
  @MappedProperty(value = "first_name")
  private String firstName;

  /**
   * The veterinarian's last name.
   *
   * <p>Mapped to the <code>last_name</code> column in the database. Cannot be null.
   */
  @MappedProperty(value = "last_name")
  private String lastName;
}
