package com.gmavrommatis.config.domain;

import com.fasterxml.jackson.annotation.JsonInclude;
import io.micronaut.core.annotation.Introspected;
import io.micronaut.data.annotation.*;
import io.micronaut.data.annotation.sql.JoinColumn;
import io.micronaut.data.annotation.sql.JoinTable;
import io.micronaut.serde.annotation.Serdeable;
import java.util.HashSet;
import java.util.Set;
import lombok.*;

/**
 * The {@code Vet} entity represents a veterinarian in the Pet Clinic domain.
 *
 * <p>Mapped to the <code>petclinic.vets</code> table, this class supports JSON
 * serialization/deserialization via Micronaut Serde, and ignores null properties during
 * serialization.
 *
 * @author GewrgiosMmavrommatis
 */
@Introspected
@Serdeable
@MappedEntity(value = "vets", schema = "petclinic")
@JsonInclude(JsonInclude.Include.NON_NULL)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class VetRelated {

  /**
   * The primary key identifier for this veterinarian.
   *
   * <p>Automatically generated by the persistence provider / database when a new record is
   * inserted. This field uniquely identifies a {@code VetRelated} instance.
   *
   * <p>Corresponds to the table primary key column (annotated with {@code @Id} and
   * {@code @GeneratedValue}).
   *
   * @see Id
   * @see GeneratedValue
   */
  @GeneratedValue @Id private Long id;

  /**
   * The veterinarian's first name.
   *
   * <p>Mapped to the {@code first_name} column in the {@code petclinic.vets} table. This value is
   * expected to be non-null in typical application use; enforce with {@code @NotNull} or a DB
   * constraint if required.
   *
   * <p>Use on DTOs or APIs: when serialized, field will appear as {@code firstName} (camelCase);
   * database column mapping is handled by {@code @MappedProperty}.
   *
   * @see io.micronaut.data.annotation.MappedProperty
   */
  @MappedProperty(value = "first_name")
  private String firstName;

  /**
   * The veterinarian's last name.
   *
   * <p>Mapped to the {@code last_name} column in the {@code petclinic.vets} table. This value is
   * expected to be non-null in typical application use; enforce with {@code @NotNull} or a DB
   * constraint if required.
   *
   * @see io.micronaut.data.annotation.MappedProperty
   */
  @MappedProperty(value = "last_name")
  private String lastName;

  /**
   * The set of specialties assigned to this veterinarian.
   *
   * <p>Represents the owning side of a many-to-many relationship between vets and specialties. The
   * association is materialized in the {@code petclinic.vet_specialties} join table with {@code
   * vet_id} and {@code specialty_id} join columns.
   *
   * <p>Cascade options include {@code PERSIST} and {@code UPDATE} to propagate saves/updates to
   * associated {@code SpecialtyRelated} entities. Choose cascade behavior carefully — using {@code
   * Cascade.ALL} will also propagate removals, which may not be desired for shared lookup/reference
   * entities like specialties.
   *
   * <p>The collection is initialized to an empty {@link HashSet} to avoid {@code
   * NullPointerException} when iterating or adding elements. For bidirectional consistency, ensure
   * updates are mirrored on the inverse side (the {@code SpecialtyRelated.vets} collection) when
   * modifying relationships.
   *
   * <p>Be cautious with JSON serialization: large or cyclic graphs may cause expensive
   * serialization or recursion issues. Use DTOs or explicit fetch strategies for API responses.
   *
   * @see Relation
   * @see JoinTable
   * @see SpecialtyRelated
   */
  @Relation(
      value = Relation.Kind.MANY_TO_MANY,
      cascade = {Relation.Cascade.PERSIST, Relation.Cascade.UPDATE} // or Cascade.ALL
      )
  @JoinTable(
      name = "vet_specialties",
      schema = "petclinic",
      joinColumns = {@JoinColumn(name = "vet_id")},
      inverseJoinColumns = {@JoinColumn(name = "specialty_id")})
  private Set<SpecialtyRelated> specialties = new HashSet<>();
}
