package com.gmavrommatis.config.domain;

import com.fasterxml.jackson.annotation.JsonInclude;
import io.micronaut.core.annotation.Introspected;
import io.micronaut.data.annotation.*;
import io.micronaut.data.annotation.sql.JoinColumn;
import io.micronaut.data.annotation.sql.JoinTable;
import io.micronaut.serde.annotation.Serdeable;
import java.util.HashSet;
import java.util.Set;
import lombok.*;

/**
 * The {@code Vet} entity represents a veterinarian in the Pet Clinic domain.
 *
 * <p>Mapped to the <code>petclinic.vets</code> table, this class supports JSON
 * serialization/deserialization via Micronaut Serde, and ignores null properties during
 * serialization.
 *
 * @author GewrgiosMmavrommatis
 */
@Introspected
@Serdeable
@MappedEntity(value = "vets", schema = "petclinic")
@JsonInclude(JsonInclude.Include.NON_NULL)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class VetRelated {

  /**
   * The primary key identifier for this veterinarian.
   *
   * <p>Automatically generated by the persistence provider / database when a new record is
   * inserted. This field uniquely identifies a {@code VetRelated} instance.
   *
   * <p>Corresponds to the table primary key column (annotated with {@code @Id} and
   * {@code @GeneratedValue}).
   *
   * @see Id
   * @see GeneratedValue
   */
  @GeneratedValue @Id private Long id;

  /**
   * The veterinarian's first name.
   *
   * <p>Mapped to the {@code first_name} column in the {@code petclinic.vets} table. This value is
   * expected to be non-null in typical application use; enforce with {@code @NotNull} or a DB
   * constraint if required.
   *
   * <p>Use on DTOs or APIs: when serialized, field will appear as {@code firstName} (camelCase);
   * database column mapping is handled by {@code @MappedProperty}.
   *
   * @see io.micronaut.data.annotation.MappedProperty
   */
  @MappedProperty(value = "first_name")
  private String firstName;

  /**
   * The veterinarian's last name.
   *
   * <p>Mapped to the {@code last_name} column in the {@code petclinic.vets} table. This value is
   * expected to be non-null in typical application use; enforce with {@code @NotNull} or a DB
   * constraint if required.
   *
   * @see io.micronaut.data.annotation.MappedProperty
   */
  @MappedProperty(value = "last_name")
  private String lastName;

  /**
   * The set of specialties assigned to this veterinarian.
   *
   * <p>Represents the <strong>owning side</strong> of a many-to-many relationship between
   * veterinarians and specialties. The association is materialized in the
   * {@code petclinic.vet_specialties} join table using {@code vet_id} and
   * {@code specialty_id} columns.
   *
   * <p>This side controls the join table and is therefore responsible for inserting and
   * updating relationship rows when a veterinarian is created or modified.
   *
   * <p>The collection is initialized to an empty {@link HashSet} to avoid {@link
   * NullPointerException} when iterating or adding elements.
   *
   * <p>Only {@code UPDATE} cascade is enabled. In this domain, {@code SpecialtyRelated}
   * entities are treated as <strong>pre-existing, shared reference data</strong>.
   *
   * <p>When creating a new veterinarian, specialties are expected to already exist in the
   * database. Persisting the veterinarian inserts rows into the join table, not new
   * specialty records.
   *
   * <p>{@code PERSIST} is intentionally excluded to prevent accidental recreation or
   * duplication of existing specialties. Using {@code Cascade.ALL} would also propagate
   * removals, which is dangerous for shared lookup entities.
   *
   * <p>For bidirectional consistency, relationship changes should also be reflected on the
   * inverse side ({@code SpecialtyRelated.vets}) when modifying associations.
   *
   * <p>Be cautious with JSON serialization. Many-to-many graphs can easily become large or
   * cyclic. Use DTO mapping or explicit fetch strategies for API responses.
   *
   * @see Relation
   * @see JoinTable
   * @see SpecialtyRelated
   */
  @Relation(
      value = Relation.Kind.MANY_TO_MANY,
      cascade = {
        Relation.Cascade.UPDATE
      } // in our case we want only UPDATE as we always expect Specialties to exist and Join table
      // rows are always inserted to link the vet with the specialties.
      // with persist, we would recreate the existing specialties.
      )
  @JoinTable(
      name = "vet_specialties",
      schema = "petclinic",
      joinColumns = {@JoinColumn(name = "vet_id")},
      inverseJoinColumns = {@JoinColumn(name = "specialty_id")})
  private Set<SpecialtyRelated> specialties = new HashSet<>();
}
